default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_rspec
  pool: 15
  username: root
  password:

test:
  <<: *default
  database: test_rspec_test
